language: java
jdk:
    - openjdk7
    - oraclejdk8
addons:
  hosts:
    - whatever
  hostname: whatever
branches:
  only:
    - master
services:
  - redis-server
script: "mvn clean package -P travis"
after_success:
  - mvn clean test jacoco:report coveralls:report